services:
  chat_db:
    image: postgres:17.2
    ports:
      - 5432:5432
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: chat
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    restart: no
    secrets:
      - postgres_password

secrets:
  postgres_password:
    file: ./secrets/postgres_password